### ISSUE TITLE
Godot 4.1 http request has different arguments

### ISSUE THREAD

**Issue by LuggageGoblin** [amzker/Gsheet_Godot#1]
I am currently trying to use this in godot 4.1 and the argument requirements for the $HTTPRequest.request has different argument requirements, I mainly only need the doPost function to work, but I can't even get a failed execution to appear on the webapp, for some reason godot isn't able to connect to it, is there something critical that requires the use of the doGet function in the webapp? I was able to run doPost successfully by declaring the variables manually, but nothing when I try to use $HTTPRequest.request(posturl,headers,HTTPClient.METHOD_POST,""), this is what I am trying to use as a substitute since the 4th argument calls for a string, and the 3rd argument calls for the method in godot 4.1. Any help is appreciated

**Comment by amzker** [comment]
your code is correct based on godot 4.x latest docs. 

for doPost requirment is that , 

at appscript side:

parameters should be defined and it should be deployed

at requesting side:

you pass parameters.


print your variables in godot and see.
try using curl , if that works to checkout if the issue is at godot side or at appscript side

**Comment by LuggageGoblin** [comment]
I have the parameters defined in the appscript, and deployed it, I'm not familiar with using curl so I couldn't test it too well, I used a debug print to get the posturl in godot, I removed the webapp url portion but here is what I am trying to send as parameters: -wkQ/exec?name=doggie&points=1362&money=1400&iapspent=0&dogspent=0&abstract=100&qscore=2381.87&click=4&passive=1&time=0-5&sheetname=PlayerData I tried using the full link with a -X -https://... in my powershell, but got back errors about the & character so I don't think I used curl correctly, do you have any other advice?

**Comment by amzker** [comment]
`curl -X POST -d "name=doggie&points=1362&money=1400&iapspent=0&dogspent=0&abstract=100&qscore=2381.87&click=4&passive=1&time=0-5&sheetname=PlayerData" http://~.wkQ/exec`

I don't see issue with & at all, maybe powershell is thinking & as built in &, try by putting url into " ".


`curl -X POST -d "name=doggie^&points=1362^&money=1400^&iapspent=0^&dogspent=0^&abstract=100^&qscore=2381.87^&click=4^&passive=1^&time=0-5^&sheetname=PlayerData" http://~wkQ/exec`

btw i will update code tomorrow, this was prototype code and we should be actually sending data rather than direct url.

**Comment by LuggageGoblin** [comment]
I tried how you did curl in the video as a test for POST with -H "Content-Type..." -H "Content-Length..." -X POST "url" and Powershell said it was having trouble with the headers, this is my first time using curl, and apps script or any web applications so thank you for the patience and responding so quickly, once I am able to get godot to add data to my google sheet I will be over the last difficult part of my project.

**Comment by amzker** [comment]
see video one should work fine.

`curl -H "Content-Type: application/json" -H "Content-Length: 0" -X POST "https://script.google.com/macros/s/~"`


here you go

**Comment by LuggageGoblin** [comment]
Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Content-Type: application/json" value of type
"System.String" to type "System.Collections.IDictionary".
At line:1 char:9
+ curl -H "Content-Type: application/json" -H "Content-Length: 0" -X PO ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
This is what gets returned as an error when I tried it, not sure what the issue is

**Comment by amzker** [comment]
invoke web request? i am not fimiliar with windows commands 

https://curl.se/windows/dl-8.4.0_6/curl-8.4.0_6-win64-mingw.zip

download curl and use it in cmd , that would be better.

although you can try this


`Invoke-WebRequest -Uri "https://script.google.com/~" -Method Post -Headers @{"Content-Type"="application/json"; "Content-Length"="0"}`

**Comment by LuggageGoblin** [comment]
I downloaded curl and tried the command you suggested and neither of them worked,

in PowerShell it said: Invoke-WebRequest : The remote server returned an error: (401) Unauthorized.

in cmd I got back a large block of text that looks like it describes an error message that says: Sorry, unable to open the file at this time. Please check the address and try again. I looked to see on the apps script's execution page to check to see if it ran at all, and there was nothing

**Comment by amzker** [comment]
unauthorised meane there is permission issue at appscript site. debugging this way is hard, you can send me telegram at @amzker  . check deploy permissions

**Comment by LuggageGoblin** [comment]
It was the deploy permissions, I'm not sure when it got set to only giving myself access, but as soon as I changed it,. it started working, thank you for help trouble shooting, if I have any further issues I'll reach out again
